Update UI
youenPlusquellec/KikeOu pull request #6
Opened 2021-12-17 13:43 UTC by youenPlusquellec

2021-12-17 14:04 UTC, wilfried7 approved these changes

2021-12-17 14:15 UTC, zartech22 requested changes
J'ai pas encore testé sur téléphone

2021-12-17 14:15 UTC, zartech22 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
On peut virer le "exported". ça permet de rendre l'activity disponible aux autres application via un Intent

2021-12-17 14:15 UTC, zartech22 commented on app/src/main/AndroidManifest.xml
>              android:exported="true" />
Idem pour l'exported

2021-12-17 14:15 UTC, zartech22 commented on app/src/main/java/com/example/kikeou/CoworkersFragment.kt
> +        val agenda3 = Agenda(3, "moi" ,50, "ma photo", listOf(contact1, contact2), listOf(loc1, loc2), false)
Normal que ça reste "ma photo" ?

2021-12-17 14:15 UTC, zartech22 commented on app/src/main/java/com/example/kikeou/ProfileFragment.kt
> +        binding.weekText.inputFilterNumberRange(0..52)
On devrait pas commencer à 1 🤔 ?

2021-12-17 14:15 UTC, zartech22 commented on app/src/main/res/layout/fragment_coworkers.xml
> -                android:textColor="@color/black"
La couleur est totalement supprimée, pas remplacée ?

2021-12-17 14:15 UTC, zartech22 commented on app/src/main/java/com/example/kikeou/ProfileDetailsActivity.kt
> +        if (agendaJson != null)
Beaucoup de vérification si l'agenda n'est pas null, on aurait pas moyen de refactoriser un peu ? Sachant que s'il est vide, on peut rien afficher... À part une belle erreur ?

2021-12-17 14:31 UTC, youenPlusquellec commented on app/src/main/java/com/example/kikeou/ProfileFragment.kt
> +        binding.weekText.inputFilterNumberRange(0..52)
Nop, c'est du strictement supérieur de ce que j'ai pu voir. Sinon on peut pas commencer à 1

2021-12-17 14:32 UTC, youenPlusquellec commented on app/src/main/res/layout/fragment_coworkers.xml
> -                android:textColor="@color/black"
Ouai, comme ça elle adopte les couleurs de base de l'application

2021-12-18 15:29 UTC, zartech22 commented on app/src/main/res/layout/fragment_coworkers.xml
> -                android:textColor="@color/black"
Ok, ok 👍

2021-12-18 15:42 UTC, zartech22 approved these changes

2021-12-18 15:52 UTC, zartech22 commented
Les images par défaut pour l'utilisateur ne se voient pas trop en thème sombre.
Dans la galerie d'avatar :
* L'image en bas à gauche ne se charge pas, c'est normal ou c'est l'image par défaut ?
* Serait-il possible d'ajouter un petit espacement entre les éléments ?

2021-12-18 23:49 UTC, zartech22 approved these changes

2021-12-19 00:17 UTC, zartech22 approved these changes

2021-12-19 00:18 UTC, merged